# Create a directory in your home directory called ".<username for your computer>-conf".
# Copy this file into that directory and name it uh-groupings-ui-3-0-overrides.properties.
# Note that properties filename will be temporary until UH Groupings 3.0 is complete.
# Fill in all blank values.

# Better Auth / Microsoft Entra ID.
BETTER_AUTH_SECRET=
BETTER_AUTH_URL=
ENTRA_CLIENT_ID=
ENTRA_TENANT_ID=
ENTRA_CERT_THUMBPRINT=

# Override BASE64-encoded, 32 Bytes in length (for HS256 algorithm) JWT secret key.
JWT_SECRET_KEY=
