name: Generate badges

on:
  push:
    branches: [main]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'Groupings Project'
          git config --global user.email 'actions@noreply.its.hawaii.edu'

      - name: Create the badges branch if it doesn't exist
        run: |
          branch_name="badges"
          if ! git ls-remote --exit-code origin refs/heads/$branch_name; then
            echo "Branch $branch_name does not exist. Creating it..."
            git checkout --orphan $branch_name
            git rm -rf .
            git commit --allow-empty -m "Create $branch_name branch"
            git push -u origin $branch_name
          else
            echo "Branch $branch_name already exists."
          fi

  generate-badges:
    needs: create-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Installing dependencies
        run: |
          cd ui
          npm install

      - name: Tests
        run: |
          cd ui
          npm run test:coverage

      - name: Switch to badges branch
        run: |
          git fetch
          git switch badges

      - name: Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: "*"
          badges-icon: vitest
          coverage-summary-path: ui/coverage/coverage-summary.json
          no-commit: true
          target-branch: badges

      - name: Commit and push badges
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'Groupings Project'
            git config --global user.email 'actions@noreply.its.hawaii.edu'
            git add *.svg
            git commit -m "Autogenerated Vitest badges" *.svg
            git push origin badges -f
          fi
