name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vitest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd ui
          npm install

      - name: Run ESLint
        run: |
          cd ui
          npm run lint

      - name: Run Vitest Tests
        run: |
          cd ui
          npm run test
